name: Setup Environment
description: Checkout repositories, install dependencies, and generate regions_envs.json file
inputs:
  env_type:
    description: 'Environment type (prod, dev, uat)'
    required: true
  repo_token:
    description: 'GitHub token for accessing private repositories'
    required: true
  review_gitops_path:
    description: 'Path to the Review GitOps repository'
    required: true
  terraform_repo_path:
    description: 'Path to the Terraform repository'
    required: true
  argocd_gitops_path:
    description: 'Path to the ArgoCD GitOps repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Review-GitOps
      uses: actions/checkout@v2
      with:
        repository: redreveal/review-gitops
        token: ${{ inputs.repo_token }}
        path: ${{ inputs.review_gitops_path }}

    - name: Checkout Terraform Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-terraform
        token: ${{ inputs.repo_token }}
        path: ${{ inputs.terraform_repo_path }}

    - name: Checkout ArgoCD-GitOps Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/argocd-gitops-versions
        token: ${{ inputs.repo_token }}
        path: ${{ inputs.argocd_gitops_path }}

    - name: Install yq, jq, and Helm
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
        sudo apt-get install -y jq
        curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
      shell: bash

    - name: Generate regions_envs.json
      uses: actions/github-script@v5
      with:
        script: |
          const regions_envs = [];
          const envTypes = ['prod', 'dev', 'uat'];
          const targetEnv = envTypes.includes('${{ inputs.env_type }}') ? '${{ inputs.env_type }}' : null;

          if (!targetEnv) {
            throw new Error(`Invalid environment type: ${{ inputs.env_type }}. Expected one of 'prod', 'dev', 'uat'.`);
          }

          compare.data.files.forEach(file => {
            if (file.filename.startsWith(`${targetEnv}/`)) {
              let region = file.filename.split('/')[1];
              regions_envs.push({region, env: targetEnv, branch: targetEnv === 'prod' ? 'production' : targetEnv === 'dev' ? 'develop' : 'uat'});
            }
          });

          const fs = require('fs');
          fs.writeFileSync('regions_envs.json', JSON.stringify(regions_envs));
          console.log(`Regions and Environments for ${targetEnv}: ${JSON.stringify(regions_envs)}`);
