name: Setup Repositories
description: Checkout repositories and set up the environment
inputs:
  repo_token:
    description: 'GitHub token for accessing private repositories'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Review-GitOps
      uses: actions/checkout@v2
      with:
        repository: redreveal/review-gitops
        token: ${{ inputs.repo_token }}
        path: review-gitops

    - name: Checkout Terraform Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-terraform
        token: ${{ inputs.repo_token }}
        path: terraform

    - name: Checkout ArgoCD-GitOps Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/argocd-gitops-versions
        token: ${{ inputs.repo_token }}
        path: argocd-gitops
