name: Review-GitOps Manual Modifications

on:
  push:
    branches:
      - main

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      prod_changed: ${{ steps.determine-env.outputs.prod_changed }}
      dev_changed: ${{ steps.determine-env.outputs.dev_changed }}
      uat_changed: ${{ steps.determine-env.outputs.uat_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Environment Based on Modified Files
        id: determine-env
        uses: actions/github-script@v5
        with:
          script: |
            const payload = context.payload;
            const repo = context.repo;
            let base, head;

            if (payload.pull_request) {
              base = payload.pull_request.base.sha;
              head = payload.pull_request.head.sha;
            } else {
              base = payload.before;
              head = payload.after;
            }

            const compare = await github.rest.repos.compareCommits({
              owner: repo.owner,
              repo: repo.repo,
              base: base,
              head: head
            });

            let prod_changed = false;
            let dev_changed = false;
            let uat_changed = false;

            compare.data.files.forEach(file => {
              if (file.filename.startsWith('prod/')) {
                prod_changed = true;
              } else if (file.filename.startsWith('dev/')) {
                dev_changed = true;
              } else if (file.filename.startsWith('uat/')) {
                uat_changed = true;
              }
            });

            core.setOutput('prod_changed', prod_changed);
            core.setOutput('dev_changed', dev_changed);
            core.setOutput('uat_changed', uat_changed);

  process-values-production:
    needs: determine-environment
    if: needs.determine-environment.outputs.prod_changed == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Production Environment
        uses: ./.github/actions/setup
        with:
          env_type: 'prod'
          repo_token: ${{ secrets.TOKEN }}
          review_gitops_path: 'review-gitops'
          terraform_repo_path: 'terraform'
          argocd_gitops_path: 'argocd-gitops'

      - name: Process Production Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'prod'
          regions_envs_file: 'regions_envs.json'
          msa_numbers_prefix: 'msa_numbers'
          gitops_repo_path: 'argocd-gitops'
          terraform_repo_path: 'terraform'
          review_gitops_path: 'review-gitops'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  process-values-dev:
    needs: determine-environment
    if: needs.determine-environment.outputs.dev_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repositories
        uses: ./.github/actions/setup-repos
        with:
          review_gitops_path: 'review-gitops'
          terraform_repo_path: 'terraform'
          argocd_gitops_path: 'argocd-gitops'
          repo_token: ${{ secrets.TOKEN }}

      - name: Process Dev Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'dev'
          regions_envs_file: 'review-gitops/regions_envs.json'
          msa_numbers_prefix: 'msa_numbers'
          review_gitops_path: 'review-gitops'
          terraform_repo_path: 'terraform'
          argocd_gitops_path: 'argocd-gitops'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  process-values-uat:
    needs: determine-environment
    if: needs.determine-environment.outputs.uat_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repositories
        uses: ./.github/actions/setup-repos
        with:
          review_gitops_path: 'review-gitops'
          terraform_repo_path: 'terraform'
          argocd_gitops_path: 'argocd-gitops'
          repo_token: ${{ secrets.TOKEN }}

      - name: Process UAT Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'uat'
          regions_envs_file: 'review-gitops/regions_envs.json'
          msa_numbers_prefix: 'msa_numbers'
          review_gitops_path: 'review-gitops'
          terraform_repo_path: 'terraform'
          argocd_gitops_path: 'argocd-gitops'
          github_token: ${{ secrets.GITHUB_TOKEN }}
