name: Review-GitOps Manual Modifications

on:
  push:
    branches:
      - main

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      dev_changed: ${{ steps.determine-environment.outputs.dev_changed }}
      uat_changed: ${{ steps.determine-environment.outputs.uat_changed }}
      prod_changed: ${{ steps.determine-environment.outputs.prod_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Determine Environment
        id: determine-environment
        uses: ./.github/actions/determine-environments
      - name: Setup Dependencies
        uses: ./.github/actions/dependencies


  push_production_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.prod_changed == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push Production Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'prod'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  push_dev_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.dev_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push Dev Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'dev'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  push_uat_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.uat_changed == 'true'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push UAT Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'uat'
          github_token: ${{ secrets.GITHUB_TOKEN }}
