name: Review-GitOps Manual Modifications

on:
  push:
    branches:
      - main

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      prod_changed: ${{ steps.determine-environment.outputs.prod_changed }}
      dev_changed: ${{ steps.determine-environment.outputs.dev_changed }}
      uat_changed: ${{ steps.determine-environment.outputs.uat_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Environment
        uses: ./.github/actions/determine-environments

      - name: Setup Dependencies
        uses: ./.github/actions/dependencies

  process-values-production:
    needs: determine-environment
    if: needs.determine-environment.outputs.prod_changed == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Process Production Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'prod'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  process-values-dev:
    needs: determine-environment
    if: needs.determine-environment.outputs.dev_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Process Dev Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'dev'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  process-values-uat:
    needs: determine-environment
    if: needs.determine-environment.outputs.uat_changed == 'true'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Process UAT Values
        uses: ./.github/actions/process-values
        with:
          env_type: 'uat'
          github_token: ${{ secrets.GITHUB_TOKEN }}
