name: Review-GitOps Manual Modifications

on:
  push:
    branches:
      - main

jobs:
  update-argocd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Review-GitOps
      uses: actions/checkout@v2

    - name: Determine Directory and Branch
      id: determine-directory
      run: |
        CHANGED_DIR=$(git diff --name-only HEAD~1 HEAD | grep -E 'dev/us-east-1|uat/eu-west-1|prod/us-east-1|prod/us-west-1' | head -1)
        echo "Changed Directory: $CHANGED_DIR"
        if [[ "$CHANGED_DIR" == dev/us-east-1* ]]; then
          echo "region=dev/us-east-1" >> $GITHUB_ENV
          echo "branch=develop" >> $GITHUB_ENV
        elif [[ "$CHANGED_DIR" == uat/eu-west-1* ]]; then
          echo "region=uat/eu-west-1" >> $GITHUB_ENV
          echo "branch=uat" >> $GITHUB_ENV
        elif [[ "$CHANGED_DIR" == prod/us-east-1* ]]; then
          echo "region=prod/us-east-1" >> $GITHUB_ENV
          echo "branch=production" >> $GITHUB_ENV
        elif [[ "$CHANGED_DIR" == prod/us-west-1* ]]; then
          echo "region=prod/us-west-1" >> $GITHUB_ENV
          echo "branch=production" >> $GITHUB_ENV
        fi
        echo "Region: ${{ env.region }}"
        echo "Branch: ${{ env.branch }}"

    - name: Checkout and Update Terraform Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-terraform
        token: ${{ secrets.TOKEN }}
        path: terraform

    - name: Update Terraform Repo to Latest
      run: |
        cd terraform
        git fetch origin
        git checkout ${{ env.branch }}
        git pull origin ${{ env.branch }}

    - name: Extract MSA Numbers
      run: |
        grep 'module.MSA' terraform/99_clients/main.tf | egrep -o '[0-9]+' | sort -u > msa_numbers.txt

    - name: Checkout ArgoCD-GitOps Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-argocd-gitops
        token: ${{ secrets.TOKEN }}
        path: argocd-gitops

    - name: Create/Update YAML Files in ArgoCD-GitOps
      run: |
        MSAS=$(cat msa_numbers.txt)
        for MSA in $MSAS; do
          echo "Processing MSA $MSA"
          DIRECTORY="argocd-gitops/${{ env.region }}"
          FILE="$DIRECTORY/$MSA.yaml"

          if [ -z "$DIRECTORY" ]; then
            echo "Error: DIRECTORY is not set"
            exit 1
          fi

          # Ensure the directory exists
          mkdir -p $DIRECTORY

          # Create a default versions.yaml if it doesn't exist
          VERSIONS_FILE="review-gitops/${{ env.region }}/versions.yaml"
          if [ ! -f $VERSIONS_FILE ]; then
            echo "default_all: 2024.7.29" > $VERSIONS_FILE
          fi

          # Check for MSA overrides in review-gitops
          if grep -q "$MSA" $VERSIONS_FILE; then
            OVERRIDE_VERSION=$(grep "$MSA" $VERSIONS_FILE | awk '{print $2}')
            echo "default_all: 2024.7.29\nmsas:\n   $MSA:\n          search: $OVERRIDE_VERSION" > $FILE
          else
            ln -sf ../../default.yaml $FILE
          fi
        done

    - name: Commit and Push
      run: |
        cd argocd-gitops
        git config user.email "rberisha@revealdata.com"
        git config user.name "Redon Berisha"
        git commit -m "Updated from Review-GitOps" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
