name: Review-GitOps Manual Modifications

on:
  push:
    paths:
      - 'dev/**'
      - 'prod/**'
      - 'uat/**'
      - 'gov/**'

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      dev_changed: ${{ steps.determine-environment.outputs.dev_changed }}
      uat_changed: ${{ steps.determine-environment.outputs.uat_changed }}
      prod_changed: ${{ steps.determine-environment.outputs.prod_changed }}
      gov_changed: ${{ steps.determine-environment.outputs.gov_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Determine Environment
        id: determine-environment
        uses: ./.github/actions/determine-environments
      - name: Setup Dependencies
        uses: ./.github/actions/dependencies


  push_production_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.prod_changed == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push Production Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'prod'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notify Summaries
        uses: ./.github/actions/gitops_slack_notify
        with:
          env_type: 'prod'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  push_dev_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.dev_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push Dev Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'dev'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notify Summaries
        uses: ./.github/actions/gitops_slack_notify
        with:
          env_type: 'dev'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  collect_tags_for_promotion:
    needs: determine-environment
    if: needs.determine-environment.outputs.uat_changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      msa_tags_json: ${{ steps.collect.outputs.msa_tags_json }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - name: Setup Dependencies
        uses: ./.github/actions/dependencies

      - name: Collect review MSA override versions
        id: collect
        uses: ./.github/actions/gitops_promote_images
        with:
          env_file: uat/eu-west-1/versions.yaml
          component: review


  promote_review_tags_sequential:
    name: Promote ${{ matrix.image_tag }} to UAT
    needs: [ determine-environment, collect_uat_review_tags ]
    if: needs.determine-environment.outputs.uat_changed == 'true'
    environment: uat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image_tag: ${{ fromJson(
          (
          needs.collect_uat_review_tags.outputs.msa_tags_json != '' &&
          needs.collect_uat_review_tags.outputs.msa_tags_json != '[]' &&
          needs.collect_uat_review_tags.outputs.msa_tags_json
          ) || '["__NO_TAGS__"]'
         ) }}
    steps:
      - name: Skip when no changes MSA overrides
        if: matrix.image_tag == '__NO_TAGS__'
        run: echo "No MSA override tags to promote."

      - name: Promote (replace with your dispatch+await)
        if: matrix.image_tag != '__NO_TAGS__'
        run: echo "Promote image tag ${{ matrix.image_tag }}"
        # later:
        # uses: PureDiscovery/return-dispatch@main
        # uses: PureDiscovery/await-remote-run@main


  push_uat_values_to_argocd:
    needs: [determine-environment, collect_uat_review_tags, promote_review_tags_sequential]
    if: needs.determine-environment.outputs.uat_changed == 'true'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push UAT Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'uat'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notify Summaries
        uses: ./.github/actions/gitops_slack_notify
        with:
          env_type: 'uat'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  push_gov_values_to_argocd:
    needs: determine-environment
    if: needs.determine-environment.outputs.gov_changed == 'true'
    runs-on: ubuntu-latest
    environment: gov
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Repositories
        uses: ./.github/actions/setup
        with:
          repo_token: ${{ secrets.TOKEN }}

      - name: Push Gov Values to ArgoCD
        uses: ./.github/actions/push_values_to_argocd_gitops_repo
        with:
          env_type: 'gov'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notify Summaries
        uses: ./.github/actions/gitops_slack_notify
        with:
          env_type: 'gov'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
