name: Review-GitOps Workflow

on:
  repository_dispatch:
    types: [update-argocd]

jobs:
  update-argocd:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Client Payload
      id: extract_payload
      run: echo "::set-output name=branch::${{ github.event.client_payload.branch }}"

    - name: Checkout Review-GitOps
      uses: actions/checkout@v2

    - name: Checkout Terraform Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-terraform
        token: ${{ secrets.TOKEN }}
        ref: "${{ steps.extract_payload.outputs.branch }}"
        path: terraform

    - name: Determine Directory and Extract MSA Numbers
      run: |
        BRANCH_NAME="${{ steps.extract_payload.outputs.branch }}"
        echo "Branch Name: $BRANCH_NAME"
        if [[ "$BRANCH_NAME" == "develop" ]]; then
          DIRECTORY="argocd-gitops/dev/us-east-1"
          MAIN_TF="dev/us-east-1/99_clients/main.tf"
        elif [[ "$BRANCH_NAME" == "staging" ]]; then
          DIRECTORY="argocd-gitops/uat/eu-west-1"
          MAIN_TF="uat/eu-west-1/99_clients/main.tf"
        elif [[ "$BRANCH_NAME" == "production" ]]; then
          DIRECTORY="argocd-gitops/prod"
          MAIN_TF_PATTERN="prod/*/99_clients/main.tf"
        fi

        if [[ -n "$MAIN_TF" ]]; then
          grep 'module.MSA' terraform/$MAIN_TF | egrep -o '[0-9]+' | sort -u > msa_numbers.txt
        elif [[ -n "$MAIN_TF_PATTERN" ]]; then
          for MAIN_TF in $(find terraform -path "terraform/$MAIN_TF_PATTERN"); do
            REGION=$(echo $MAIN_TF | awk -F'/' '{print $2}')
            grep 'module.MSA' $MAIN_TF | egrep -o '[0-9]+' | sort -u >> msa_numbers.txt
          done
          sort -u msa_numbers.txt -o msa_numbers.txt
        fi

