name: Review-GitOps Workflow

on:
  repository_dispatch:
    types: [update-argocd]

jobs:
  update-argocd:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Client Payload
      id: extract_payload
      run: echo "::set-output name=branch::${{ github.event.client_payload.branch }}"

    - name: Checkout Review-GitOps
      uses: actions/checkout@v2

    - name: Checkout Terraform Repo
      uses: actions/checkout@v2
      with:
        repository: redreveal/red-terraform
        token: ${{ secrets.TOKEN }}
        ref: "${{ steps.extract_payload.outputs.branch }}"
        path: terraform

    - name: Determine Directory and Extract MSA Numbers
      run: |
        BRANCH_NAME="${{ steps.extract_payload.outputs.branch }}"
        echo "Branch Name: $BRANCH_NAME"
        if [[ "$BRANCH_NAME" == "develop" ]]; then
          DIRECTORY="argocd-gitops/review/dev/us-east-1"
          MAIN_TF="dev/us-east-1/99_clients/main.tf"
          grep 'module.MSA' terraform/$MAIN_TF | egrep -o '[0-9]+' | sort -u > msa_numbers.txt
        elif [[ "$BRANCH_NAME" == "uat" ]]; then
          DIRECTORY="argocd-gitops/review/uat/eu-west-1"
          MAIN_TF="uat/eu-west-1/99_clients/main.tf"
          grep 'module.MSA' terraform/$MAIN_TF | egrep -o '[0-9]+' | sort -u > msa_numbers.txt
        elif [[ "$BRANCH_NAME" == "production" ]]; then
          DIRECTORY="argocd-gitops/review/prod"
          MAIN_TF_PATTERN="prod/*/99_clients/main.tf"
          for MAIN_TF in $(find terraform -path "terraform/$MAIN_TF_PATTERN"); do
            REGION=$(echo $MAIN_TF | awk -F'/' '{print $3}')
            grep 'module.MSA' $MAIN_TF | egrep -o '[0-9]+' | sort -u > msa_numbers_${REGION}.txt
          done
        fi

        echo "Directory: $DIRECTORY"
        if [[ -f msa_numbers.txt ]]; then
          cat msa_numbers.txt
        else
          for REGION in $(find terraform/prod -maxdepth 1 -mindepth 1 -type d -exec basename {} \;); do
            echo "MSAs for region $REGION:"
            cat msa_numbers_${REGION}.txt
          done
        fi

    - name: Checkout ArgoCD-GitOps
      uses: actions/checkout@v2
      with:
        repository: redreveal/argocd-gitops-versions
        token: ${{ secrets.TOKEN }}
        path: argocd-gitops

    - name: Create Symlinks for New MSAs
      run: |
        if [[ -f msa_numbers.txt ]]; then
          MSAS=$(cat msa_numbers.txt)
          for MSA in $MSAS; do
            echo "Processing MSA $MSA"
            DIRECTORY="${{ env.DIRECTORY }}"
            FILE="$DIRECTORY/$MSA.yaml"
            mkdir -p $DIRECTORY
            if [ ! -L $FILE ] && [ ! -f $FILE ]; then
              ln -sf ./default_values.yaml $FILE
            fi
          done
        else
          for REGION in $(find terraform/prod -maxdepth 1 -mindepth 1 -type d -exec basename {} \;); do
            MSAS=$(cat msa_numbers_${REGION}.txt)
            for MSA in $MSAS; do
              echo "Processing MSA $MSA for region $REGION"
              DIRECTORY="argocd-gitops/review/prod/$REGION"
              FILE="$DIRECTORY/$MSA.yaml"
              mkdir -p $DIRECTORY
              if [ ! -L $FILE ] && [ ! -f $FILE ]; then
                ln -sf ./default_values.yaml $FILE
              fi
            done
          done
        fi

    - name: Commit and Push
      run: |
        cd argocd-gitops
        git config user.email "rberisha@revealdata.com"
        git config user.name "Redon Berisha"
        git add .
        git commit -m "Added symlinks for new MSAs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
